//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.14 at 01:21:25 PM WAT 
//


package bookmanagementsystem.books;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BookDetails" type="{bookmanagementsystem/books}BookDetails"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bookDetails"
})
@XmlRootElement(name = "GetBookDetailsResponse")
public class GetBookDetailsResponse {

    @XmlElement(name = "BookDetails", required = true)
    protected BookDetails bookDetails;

    /**
     * Gets the value of the bookDetails property.
     * 
     * @return
     *     possible object is
     *     {@link BookDetails }
     *     
     */
    public BookDetails getBookDetails() {
        return bookDetails;
    }

    /**
     * Sets the value of the bookDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link BookDetails }
     *     
     */
    public void setBookDetails(BookDetails value) {
        this.bookDetails = value;
    }

}
